title: App Support Center
description: >-
  Frequently Asked Questions and Support for BudgetNinja and other apps.
email: your-email@example.com # İsteğe bağlı: iletişim için
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://faq.serhatgurkan.com" # the base hostname & protocol for your site, e.g. http://example.com

# Collections for FAQs
collections:
  budgetninja_faq:
    output: false # Don't create individual pages for each FAQ item
  # Gelecekteki uygulamalar için koleksiyonları buraya ekleyin
  # another_app_faq:
  #   output: false

# Markdown işlemcisi (isteğe bağlı, kramdown varsayılandır)
markdown: kramdown

# Build settings
theme: minima # Using minima as a base, but overriding with local layouts/css
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE